name: master deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2
      - name: Build
        run: |
          pnpm i --frozen-lockfile
          pnpm run build
  deploy-s3:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
            submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Configure AWS Credentials for S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Copy files to the s3 website content bucket
        run: aws s3 sync build s3://gosling-lang
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.CF_DISTRIBUTION_ID}} --paths "/*"
